name: fuzz
on: [ workflow_dispatch ]

jobs:
  fuzz:
    name: fuzz
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.16.x'
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: script/fuzz-timeout 60
      - uses: peter-evans/create-pull-request@v3.8.2
        with:
          branch: fuzz-update
          title: update fuzz data
          delete-branch: true
          body: update fuzz data
